[117542]
unsolved = "..2.987...6.4......5.7....1174.8.3.92.5..3.........1..9..............8....3.24.6."
solved   = "432198756761435298859762431174586329285913674396247185928671543647359812513824967"

[117602]
unsolved = "...4..3.1.6.....2.5....76.8.....5...2........1.....863.9..2.48..8..5......76....9"
solved   = "729468351864531927513297648936845172278316594145972863691723485482159736357684219"

[118010]
unsolved = "2......7...8..3.4...36...8.5......31..1.2..6....9.......217.8...6...8..4....5.7.."
solved   = "246589173958713642173642589594867231381425967627931458432176895765298314819354726"

[118011]
unsolved = ".9..8..61..519.3..2..4..9.....5......6..1..8...4.3.......7..2...1.....36....5...."
solved   = "793285461645197328281463957139578642562914783874632195358746219417829536926351874"

[118037]
unsolved = ".4.6...3...5..........3.7.695..681.....71...2..4.........54.821.....16....6......"
solved   = "741682935635197284289435716952368147863714592174259368397546821428971653516823479"

[118045]
unsolved = ".4....971.....6.....89.....2.....3.66.7.158.2......7.59..8.....8.....53917...2..."
solved   = "346528971792136458518947263251789346637415892489263715963854127824671539175392684"

[118049]
unsolved = "615.8...........6..4...3.2..9..........7....55861....2...6.......38..7..4..35...9"
solved   = "615287493329415867847963521792538146134726985586149372951674238263891754478352619"

[118087]
unsolved = "..7.......6.8...3.....3.5.8...51...427..891....6.........76.941.....18....8......"
solved   = "837125496561894237492637518983516724274389165156472389325768941649251873718943652"

[118091]
unsolved = "...7..9...3958.2........3542....35..8.....1.........96.5429.......4...1...7.6...."
solved   = "425736981139584267768129354291673548876945132543812796654291873382457619917368425"

[118096]
unsolved = ".3.4....9.8..39...7...6..5.....2..1...3..14855.......21..6.......4........7...528"
solved   = "236415879485739261719862354948526713623971485571348692152683947894257136367194528"

[118219]
unsolved = "..3.6.4194..281.5................2..2..943...6.7........1........25.....5.4...968"
solved   = "823765419496281753715439826139657284258943671647128395961874532382596147574312968"

[118224]
unsolved = ".6...5.7........2.281.4.....3.......1428....7...9....1...2.......54..9..6..51...3"
solved   = "469325178573681429281749635937154862142863597856972341318296754725438916694517283"

[118225]
unsolved = "258..1.4.6..4......1....9.........3.972..5....3..24..85..2.91..7...5....3..6....."
solved   = "258391647697482351413567982845716239972835416136924578584279163769153824321648795"

[118242]
unsolved = "..92.1...8..5.32.......4.75.......343..8..6..2....69..7.........6..184.......9..1"
solved   = "579281346846573219132694875687925134391847652254136987713462598965718423428359761"

[118243]
unsolved = "......1.....82.....48..7.6..26......8........7..1....5...56.87...2..4...5.9..3..4"
solved   = "237645198965821743148397562326458917851279436794136285413562879672984351589713624"

[118244]
unsolved = "8..635.2...7.1.854...............6..6..487...1.9........5........62.....2.8...413"
solved   = "841635927367912854952874361574129638623487195189563742415398276736241589298756413"

[118245]
unsolved = ".....9.....13......2....3748.....6.9......7.59.7.451.83..1.....1.....56347...8..."
solved   = "738469251541327896629581374854713629213896745967245138396152487182974563475638912"

[118250]
unsolved = "2..9.....714..6.9..6....3.........8.357..1....8..79..41..7.36..5...1....8..2....."
solved   = "235947816714836295968125347491562783357481962682379154149753628523618479876294531"

[118252]
unsolved = "...89..3..64...7..5.........93...........3.5.7.......2.2.4...71.4.7..9..6..1...48"
solved   = "172896435364251789589347216493582167216973854758614392925438671841765923637129548"

[118254]
unsolved = "..........3.2..9682..3.8..7...98..4..2.73....1..5.6.......7...56.....8...5...3126"
solved   = "786159234531247968249368517365981742928734651174526389813672495692415873457893126"

[118288]
unsolved = "..9..7...85...............8...6..12....4..7....67.29.5..72.93....2..1...964..5..."
solved   = "429587631851936247673124598798653124215498763346712985187249356532861479964375812"

[271829]
unsolved = "4..839.5...97..........42....8....943.....5.2....1.7.6..3..2.75.........5..697..3"
solved   = "421839657639725841857164239218576394376948512945213786163482975792351468584697123"

